### ISSUE TITLE
Add binarized images for all text lines

### ISSUE THREAD

**Issue by wrznr** [jze/ocropus-model_fraktur#3]
This is a great repo. Many thanks for your efforts. A minor inconvenience: Not all text lines have corresponding binarized image attached to them (e.g. `training/munzinger_afdc9d7e6c3b9ca2df0071bac955f822.gt.txt`). It would be wonderful if they could be added.

**Comment by jze** [comment]
I have uploaded the binarized images in commit 60bb1c647ee3dd3d9ee611c163b017cb2f45a4e0
